export interface PersianHolidayEntry {
  calendar: "jalali" | "gregorian" | "hijri"
  /** Whether this is an official day off, as opposed to a commemorative occasion. */
  official: boolean
  title: string
  /** 1-indexed month in its own calendar field above. */
  month: number
  day: number
}

export const persianHolidaysData: PersianHolidayEntry[] = [
  {
    calendar: "jalali",
    official: true,
    title: "جشن نوروز/جشن سال نو",
    month: 1,
    day: 1,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی شادی",
    month: 3,
    day: 20,
  },
  { calendar: "jalali", official: true, title: "عیدنوروز", month: 1, day: 2 },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی نوروز",
    month: 3,
    day: 21,
  },
  { calendar: "jalali", official: true, title: "عیدنوروز", month: 1, day: 3 },
  { calendar: "jalali", official: true, title: "عیدنوروز", month: 1, day: 4 },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی هواشناسی",
    month: 3,
    day: 23,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز امید، روز شادباش نویسی",
    month: 1,
    day: 6,
  },
  {
    calendar: "jalali",
    official: false,
    title: "زادروز اَشو زرتشت، اَبَراِنسان بزرگ تاریخ",
    month: 1,
    day: 6,
  },
  {
    calendar: "hijri",
    official: false,
    title: "ولادت امام حسن مجتبی علیه السلام",
    month: 9,
    day: 15,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی تئاتر",
    month: 3,
    day: 27,
  },
  {
    calendar: "jalali",
    official: false,
    title: "جشن آبانگاه",
    month: 1,
    day: 10,
  },
  { calendar: "hijri", official: false, title: "شب قدر", month: 9, day: 18 },
  {
    calendar: "hijri",
    official: false,
    title: "ضربت خوردن حضرت علی علیه السلام",
    month: 9,
    day: 19,
  },
  {
    calendar: "jalali",
    official: true,
    title: "روز جمهوری اسلامی",
    month: 1,
    day: 12,
  },
  {
    calendar: "jalali",
    official: true,
    title: "جشن سیزده به در",
    month: 1,
    day: 13,
  },
  {
    calendar: "hijri",
    official: true,
    title: "شهادت حضرت علی علیه السلام",
    month: 9,
    day: 21,
  },
  { calendar: "hijri", official: false, title: "شب قدر", month: 9, day: 22 },
  {
    calendar: "jalali",
    official: false,
    title: "سروش روز،جشن سروشگان",
    month: 1,
    day: 17,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی بهداشت",
    month: 4,
    day: 7,
  },
  {
    calendar: "jalali",
    official: false,
    title: "فروردین روز،جشن فروردینگان",
    month: 1,
    day: 19,
  },
  {
    calendar: "hijri",
    official: true,
    title: "عید سعید فطر",
    month: 10,
    day: 1,
  },
  {
    calendar: "hijri",
    official: true,
    title: "تعطیل به مناسبت عید سعید فطر",
    month: 10,
    day: 2,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز دندانپزشک",
    month: 1,
    day: 23,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز بزرگداشت عطار نیشابوری",
    month: 1,
    day: 25,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز ارتش جمهوری اسلامی ایران",
    month: 1,
    day: 29,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز علوم آزمایشگاهی، زاد روز حکیم سید اسماعیل جرجانی",
    month: 1,
    day: 30,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز بزرگداشت سعدی",
    month: 2,
    day: 1,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "جشن گیاه آوری؛ روز زمین",
    month: 4,
    day: 22,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روزبزرگداشت شیخ بهایی؛ روزملی کارآفرینی؛ روز معماری",
    month: 2,
    day: 3,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی طراحی و گرافیک",
    month: 4,
    day: 27,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز ملی روانشناس و مشاور",
    month: 2,
    day: 9,
  },
  {
    calendar: "jalali",
    official: false,
    title: "جشن چهلم نوروز؛ روز ملی خلیج فارس",
    month: 2,
    day: 10,
  },
  { calendar: "jalali", official: false, title: "روز معلم", month: 2, day: 12 },
  {
    calendar: "gregorian",
    official: false,
    title: "روزجهانی  کارگر",
    month: 5,
    day: 1,
  },
  {
    calendar: "jalali",
    official: false,
    title: "جشن میانه بهار/جشن بهاربد؛ روز شیراز",
    month: 2,
    day: 15,
  },
  {
    calendar: "hijri",
    official: true,
    title: "شهادت امام جعفر صادق علیه السلام",
    month: 10,
    day: 25,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی ماما",
    month: 5,
    day: 5,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی صلیب سرخ و هلال احمر",
    month: 5,
    day: 8,
  },
  {
    calendar: "hijri",
    official: false,
    title: "ولادت حضرت معصومه سلام الله علیها و روز دختران",
    month: 11,
    day: 1,
  },
  {
    calendar: "jalali",
    official: false,
    title: "زادروز مریم میرزاخانی ریاضیدان ایرانی، روز جهانی زن در ریاضیات",
    month: 2,
    day: 22,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی پرستار",
    month: 5,
    day: 12,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز بزرگداشت فردوسی",
    month: 2,
    day: 25,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز ارتباطات و روابط عمومی",
    month: 2,
    day: 27,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز بزرگداشت حکیم عمر خیام",
    month: 2,
    day: 28,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی موزه و میراث فرهنگی",
    month: 5,
    day: 18,
  },
  {
    calendar: "hijri",
    official: false,
    title: "ولادت امام  رضا علیه السلام",
    month: 11,
    day: 11,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز بهره وری و بهینه سازی مصرف",
    month: 3,
    day: 1,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز بزرگداشت ملاصدرا",
    month: 3,
    day: 1,
  },
  {
    calendar: "jalali",
    official: false,
    title: "فروریختن ساختمان متروپل در آبادان",
    month: 3,
    day: 2,
  },
  {
    calendar: "jalali",
    official: false,
    title: "فتح خرمشهر در عملیات بیت المقدس و روز مقاومت، ایثار و پیروزی",
    month: 3,
    day: 3,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز دزفول، روز مقاومت و پایداری",
    month: 3,
    day: 4,
  },
  {
    calendar: "jalali",
    official: false,
    title: "خرداد روز،جشن خردادگان",
    month: 3,
    day: 6,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی بدون دخانیات",
    month: 5,
    day: 31,
  },
  {
    calendar: "jalali",
    official: true,
    title: "رحلت حضرت امام خمینی",
    month: 3,
    day: 14,
  },
  {
    calendar: "jalali",
    official: true,
    title: "قیام 15 خرداد",
    month: 3,
    day: 15,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی محیط زیست",
    month: 6,
    day: 5,
  },
  {
    calendar: "hijri",
    official: false,
    title: "شهادت امام محمد تقی علیه السلام",
    month: 11,
    day: 29,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی صنایع دستی",
    month: 6,
    day: 10,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی مبارزه با کار کودکان",
    month: 6,
    day: 12,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز ملی گل وگیاه",
    month: 3,
    day: 25,
  },
  {
    calendar: "hijri",
    official: false,
    title: "شهادت امام محمد باقر علیه السلام",
    month: 12,
    day: 7,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی اهدای خون",
    month: 6,
    day: 14,
  },
  { calendar: "hijri", official: false, title: "روز عرفه", month: 12, day: 9 },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی پدر",
    month: 6,
    day: 16,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی بیابان زدایی",
    month: 6,
    day: 17,
  },
  {
    calendar: "hijri",
    official: true,
    title: "عید سعید قربان",
    month: 12,
    day: 10,
  },
  {
    calendar: "jalali",
    official: false,
    title: "سالروز زلزله رودبار و منجیل [1369خورشیدی]",
    month: 3,
    day: 31,
  },
  {
    calendar: "jalali",
    official: false,
    title: "جشن آب پاشونک، جشن آغاز تابستان",
    month: 4,
    day: 1,
  },
  {
    calendar: "hijri",
    official: false,
    title: "ولادت امام علی النقی الهادی علیه السلام",
    month: 12,
    day: 15,
  },
  {
    calendar: "hijri",
    official: true,
    title: "عید سعید غدیر خم",
    month: 12,
    day: 18,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی مبارزه با مواد مخدر",
    month: 6,
    day: 26,
  },
  {
    calendar: "jalali",
    official: false,
    title:
      "انفجار دفتر حزب جمهوری اسلامی و شهادت دکتر بهشتی و 72 نفر از اعضای حزب؛ روز قوه قضاییه",
    month: 4,
    day: 7,
  },
  {
    calendar: "hijri",
    official: false,
    title: "ولادت امام موسی کاظم علیه السلام",
    month: 12,
    day: 20,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز مبارزه با سلاح های شیمیایی و میکروبی",
    month: 4,
    day: 8,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز صنعت و معدن",
    month: 4,
    day: 10,
  },
  {
    calendar: "jalali",
    official: false,
    title: "زادروز بابک خرمدین، سپه‌سالار دلاور ایران",
    month: 4,
    day: 10,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز بزرگداشت صائب تبریزی",
    month: 4,
    day: 10,
  },
  {
    calendar: "jalali",
    official: false,
    title: "شلیک به پرواز 655 ایران ایر توسط ناو وینسنس [ 1367 خورشیدی ]",
    month: 4,
    day: 12,
  },
  {
    calendar: "jalali",
    official: false,
    title:
      "جشن تیرگان، بزرگداشت کمان کشیدن جان‌فدای ایران، آرش کمانگیر بر فراز البرز",
    month: 4,
    day: 13,
  },
  { calendar: "jalali", official: false, title: "روز قلم", month: 4, day: 14 },
  {
    calendar: "jalali",
    official: false,
    title: "جشن خام خواری",
    month: 4,
    day: 15,
  },
  {
    calendar: "jalali",
    official: false,
    title:
      "زادروز محمد خوارزمی، ریاضیدان و فیلسوف ایرانی و روز ملی فناوری اطلاعات",
    month: 4,
    day: 22,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز بهزیستی و تامین اجتماعی",
    month: 4,
    day: 25,
  },
  {
    calendar: "hijri",
    official: true,
    title: "تاسوعای حسینی",
    month: 1,
    day: 9,
  },
  {
    calendar: "hijri",
    official: true,
    title: "عاشورای حسینی",
    month: 1,
    day: 10,
  },
  {
    calendar: "jalali",
    official: false,
    title: "اعلام پذیرش قطعنامه 598 شورای امنیت از سوی ایران [ 1367 خورشیدی ]",
    month: 4,
    day: 27,
  },
  {
    calendar: "hijri",
    official: false,
    title: "شهادت  امام زین العابدین علیه السلام",
    month: 1,
    day: 12,
  },
  {
    calendar: "jalali",
    official: false,
    title: "اَمرداد روز،جشن  اَمردادگان",
    month: 5,
    day: 7,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز بزرگداشت شیخ شهاب الدین سهروردی",
    month: 5,
    day: 8,
  },
  {
    calendar: "jalali",
    official: false,
    title: "جشن چله تابستان",
    month: 5,
    day: 10,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "آغاز هفته جهانی شیردهی",
    month: 8,
    day: 1,
  },
  {
    calendar: "jalali",
    official: false,
    title: "سالروز صدور فرمان مشروطیت",
    month: 5,
    day: 14,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز خبرنگار",
    month: 5,
    day: 17,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی چپ دست ها",
    month: 8,
    day: 13,
  },
  {
    calendar: "jalali",
    official: false,
    title: "سالروز وقایع 28 مرداد پس از برکناری محمد مصدق‌السلطنه",
    month: 5,
    day: 28,
  },
  {
    calendar: "jalali",
    official: false,
    title: "سالروز فاجعه آتش زدن سینما رکس آبادان",
    month: 5,
    day: 28,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی عکاسی",
    month: 8,
    day: 19,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز بزرگداشت ابوعلی سینا و روز پزشک",
    month: 6,
    day: 1,
  },
  {
    calendar: "jalali",
    official: false,
    title: "آغاز هفته دولت",
    month: 6,
    day: 2,
  },
  {
    calendar: "jalali",
    official: false,
    title: "زادروز کوروش بزرگ",
    month: 6,
    day: 4,
  },
  {
    calendar: "jalali",
    official: false,
    title: "شهریور روز،جشن شهریورگان",
    month: 6,
    day: 4,
  },
  {
    calendar: "hijri",
    official: true,
    title: "اربعین حسینی",
    month: 2,
    day: 20,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز بزرگداشت محمدبن زکریای رازی و روز داروساز",
    month: 6,
    day: 5,
  },
  {
    calendar: "jalali",
    official: false,
    title:
      "انفجار در دفتر نخست‌وزیری جمهوری اسلامی ایران، روز مبارزه با تروریسم",
    month: 6,
    day: 8,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روزصنعت چاپ",
    month: 6,
    day: 11,
  },
  {
    calendar: "hijri",
    official: true,
    title: "رحلت  رسول اکرم؛شهادت امام حسن مجتبی علیه السلام",
    month: 2,
    day: 28,
  },
  {
    calendar: "jalali",
    official: false,
    title:
      "سالروز شهادت رئیسعلی دلواری، سردار بزرگ میهن و فرمانده قیام جنوب علیه اشغالگران انگلیسی",
    month: 6,
    day: 12,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز بزرگداشت ابوریحان بیرونی",
    month: 6,
    day: 13,
  },
  {
    calendar: "hijri",
    official: true,
    title: "شهادت امام رضا علیه السلام",
    month: 2,
    day: 30,
  },
  {
    calendar: "hijri",
    official: false,
    title: "هجرت پیامبر اکرم از مکه به مدینه",
    month: 3,
    day: 1,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی پیشگیری از خودکشی",
    month: 9,
    day: 10,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز سینما",
    month: 6,
    day: 21,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "حمله به برج‌های دوقلوی مرکز تجارت جهانی",
    month: 9,
    day: 11,
  },
  {
    calendar: "hijri",
    official: true,
    title: "شهادت امام حسن عسکری علیه السلام",
    month: 3,
    day: 8,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز گرامیداشت برنامه نویسان",
    month: 9,
    day: 12,
  },
  {
    calendar: "hijri",
    official: false,
    title: "میلاد رسول اکرم به روایت اهل سنت",
    month: 3,
    day: 12,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز شعر و ادب پارسی و  روز بزرگداشت استاد شهریار",
    month: 6,
    day: 27,
  },
  {
    calendar: "jalali",
    official: false,
    title: "آغاز هفته دفاع مقدس",
    month: 6,
    day: 31,
  },
  {
    calendar: "hijri",
    official: true,
    title: "میلاد رسول اکرم و امام جعفر صادق علیه السلام",
    month: 3,
    day: 17,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی صلح",
    month: 9,
    day: 21,
  },
  {
    calendar: "jalali",
    official: false,
    title: "آغاز حمله مغول به ایران در پاییز 598 خورشیدی",
    month: 7,
    day: 1,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز گرامیداشت سربازان وطن",
    month: 7,
    day: 4,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی جهانگردی",
    month: 9,
    day: 27,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز آتش نشانی و ایمنی",
    month: 7,
    day: 7,
  },
  {
    calendar: "jalali",
    official: false,
    title:
      "سقوط هواپیمای حامل جمعی از فرماندهان جنگ (کلاهدوز، نامجو، فلاحی، فکوری، جهان آرا) در سال 1360",
    month: 7,
    day: 7,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز بزرگداشت شمس تبریزی",
    month: 7,
    day: 7,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روزبزرگداشت مولوی",
    month: 7,
    day: 8,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی ناشنوایان",
    month: 9,
    day: 30,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی ترجمه و مترجم",
    month: 9,
    day: 30,
  },
  {
    calendar: "jalali",
    official: false,
    title: "مهر روز،جشن مهرگان",
    month: 7,
    day: 10,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی سالمندان",
    month: 10,
    day: 1,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "آغاز هفته جهانی فضا",
    month: 10,
    day: 4,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز دامپزشکی",
    month: 7,
    day: 14,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی معلم",
    month: 10,
    day: 5,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز ملی کودک",
    month: 7,
    day: 16,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی پست",
    month: 10,
    day: 9,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی مبارزه با حکم اعدام",
    month: 10,
    day: 10,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز بزرگداشت حافظ",
    month: 7,
    day: 20,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی دختر",
    month: 10,
    day: 11,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز پیروزی کاوه و فریدون بر ضحاک",
    month: 7,
    day: 21,
  },
  {
    calendar: "hijri",
    official: false,
    title: "ولادت امام حسن عسکری علیه السلام",
    month: 4,
    day: 8,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی استاندارد",
    month: 10,
    day: 14,
  },
  {
    calendar: "hijri",
    official: false,
    title: "وفات حضرت معصومه سلام الله علیها",
    month: 4,
    day: 10,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی عصای سفید",
    month: 10,
    day: 15,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی غذا",
    month: 10,
    day: 16,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز تربیت بدنی و ورزش",
    month: 7,
    day: 26,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی ریشه کنی فقر",
    month: 10,
    day: 17,
  },
  {
    calendar: "jalali",
    official: false,
    title: "زادروز ستارخان ملقب به سردار ملی و از سرداران جنبش مشروطه ایران",
    month: 7,
    day: 28,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز ملی کوهنورد",
    month: 7,
    day: 29,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز آمار و برنامه ریزی",
    month: 8,
    day: 1,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز بزرگداشت ابوالفضل بیهقی، تاریخ‌نگار و نویسنده ایرانی",
    month: 8,
    day: 1,
  },
  {
    calendar: "jalali",
    official: false,
    title: "سالروز ورود کوروش بزرگ به بابل در سال 539 پیش از میلاد",
    month: 8,
    day: 7,
  },
  {
    calendar: "jalali",
    official: false,
    title: "آبان روز، جشن آبانگان",
    month: 8,
    day: 10,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز دانش آموز",
    month: 8,
    day: 13,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز ملّی مازندران",
    month: 8,
    day: 14,
  },
  {
    calendar: "jalali",
    official: false,
    title: "جشن میانه پاییز",
    month: 8,
    day: 15,
  },
  {
    calendar: "hijri",
    official: false,
    title: "ولادت حضرت زینب سلام الله علیها و روز پرستار و بهورز",
    month: 5,
    day: 5,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز ملی کیفیت",
    month: 8,
    day: 18,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز کتاب و کتابخوانی",
    month: 8,
    day: 24,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی دیابت",
    month: 11,
    day: 14,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی آقایان",
    month: 11,
    day: 19,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی کودک",
    month: 11,
    day: 20,
  },
  { calendar: "jalali", official: false, title: "آذر جشن", month: 9, day: 1 },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی فلسفه",
    month: 11,
    day: 21,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز بسیج مستضعفان",
    month: 9,
    day: 5,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی مبارزه با خشونت علیه زنان",
    month: 11,
    day: 25,
  },
  {
    calendar: "jalali",
    official: false,
    title: "سالروز عملیات مروارید و روز نیروی دریایی",
    month: 9,
    day: 7,
  },
  {
    calendar: "jalali",
    official: false,
    title: "جشن آذرگان ،آذر روز",
    month: 9,
    day: 9,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی ایدز",
    month: 12,
    day: 1,
  },
  { calendar: "jalali", official: false, title: "روز بیمه", month: 9, day: 13 },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی معلولان",
    month: 12,
    day: 3,
  },
  {
    calendar: "hijri",
    official: true,
    title: "شهادت حضرت فاطمه زهرا سلام الله علیها",
    month: 6,
    day: 3,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز حسابدار",
    month: 9,
    day: 15,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز دانشجو",
    month: 9,
    day: 16,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی حقوق بشر",
    month: 12,
    day: 10,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی کوهستان",
    month: 12,
    day: 11,
  },
  {
    calendar: "jalali",
    official: false,
    title: "سالروز نجات آذربایجان",
    month: 9,
    day: 21,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز پژوهش و فنآوری",
    month: 9,
    day: 25,
  },
  {
    calendar: "jalali",
    official: false,
    title: "جشن شب یلدا، شب چلّه",
    month: 9,
    day: 30,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز میلاد خورشید؛ جشن خرم روز، نخستین جشن دیگان",
    month: 10,
    day: 1,
  },
  {
    calendar: "hijri",
    official: false,
    title: "ولادت حضرت فاطمه زهرا سلام الله علیها و روز مادر",
    month: 6,
    day: 20,
  },
  {
    calendar: "jalali",
    official: false,
    title: "زمین لرزه ی بم [1382 خورشیدی]",
    month: 10,
    day: 5,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "جشن کریسمس",
    month: 12,
    day: 25,
  },
  {
    calendar: "jalali",
    official: false,
    title: "سالروز شهادت اَشو زرتشت، اَبَراِنسان بزرگ تاریخ",
    month: 10,
    day: 5,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز بزرگداشت دوستی",
    month: 12,
    day: 25,
  },
  {
    calendar: "jalali",
    official: false,
    title: "سالروز عملیات کربلای 4 [1365 خورشیدی]",
    month: 10,
    day: 5,
  },
  {
    calendar: "jalali",
    official: false,
    title: "دی به آذر روز، دومین جشن دیگان",
    month: 10,
    day: 8,
  },
  {
    calendar: "jalali",
    official: false,
    title:
      "روز بزرگداشت یعقوب لیث صفاری (رادمان پورماهک) نخستین پادشاه ایرانی پس از اسلام",
    month: 10,
    day: 8,
  },
  {
    calendar: "jalali",
    official: false,
    title:
      "اعدام میهن‌پرستان آذری در تبریز توسط قوای اشغالگر روس [1290 خورشیدی]",
    month: 10,
    day: 9,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "جشن آغاز سال نو میلادی",
    month: 1,
    day: 1,
  },
  {
    calendar: "hijri",
    official: false,
    title: "ولادت  امام محمد باقر علیه السلام",
    month: 7,
    day: 1,
  },
  {
    calendar: "jalali",
    official: false,
    title: "شهادت سردار حاج قاسم سلیمانی [1398 خورشیدی]",
    month: 10,
    day: 13,
  },
  {
    calendar: "jalali",
    official: false,
    title: "دی به مهر روز، سومین جشن دیگان",
    month: 10,
    day: 15,
  },
  {
    calendar: "hijri",
    official: false,
    title: "شهادت امام علی النقی الهادی علیه السلام",
    month: 7,
    day: 3,
  },
  {
    calendar: "jalali",
    official: false,
    title: "غرق شدن کشتی سانچی [1396 خورشیدی]",
    month: 10,
    day: 16,
  },
  {
    calendar: "jalali",
    official: false,
    title: "شلیک به پرواز 752 هواپیمایی اوکراین [1398 خورشیدی]",
    month: 10,
    day: 18,
  },
  {
    calendar: "jalali",
    official: false,
    title: "درگذشت اکبر هاشمی رفسنجانی [1395 خورشیدی]",
    month: 10,
    day: 19,
  },
  {
    calendar: "jalali",
    official: false,
    title: "قتل امیرکبیر به دستور ناصرالدین شاه قاجار [1230 خورشیدی]",
    month: 10,
    day: 20,
  },
  {
    calendar: "hijri",
    official: false,
    title: "ولادت امام محمد تقی علیه السلام",
    month: 7,
    day: 10,
  },
  {
    calendar: "jalali",
    official: false,
    title: "دی به دین روز، چهارمین جشن دیگان",
    month: 10,
    day: 23,
  },
  {
    calendar: "hijri",
    official: true,
    title: "ولادت امام علی علیه السلام و روز پدر",
    month: 7,
    day: 13,
  },
  {
    calendar: "hijri",
    official: false,
    title: "وفات حضرت زینب سلام الله علیها",
    month: 7,
    day: 15,
  },
  {
    calendar: "jalali",
    official: false,
    title: "آتش‌سوزی و فروریختن ساختمان پلاسکو [1395 خورشیدی]",
    month: 10,
    day: 30,
  },
  {
    calendar: "jalali",
    official: false,
    title: "زادروز فردوسی",
    month: 11,
    day: 1,
  },
  {
    calendar: "jalali",
    official: false,
    title: "بهمن روز، جشن بهمنگان",
    month: 11,
    day: 2,
  },
  {
    calendar: "jalali",
    official: false,
    title: "جشن نوسره",
    month: 11,
    day: 5,
  },
  {
    calendar: "hijri",
    official: false,
    title: "شهادت امام موسی کاظم علیه السلام",
    month: 7,
    day: 25,
  },
  {
    calendar: "hijri",
    official: true,
    title: "مبعث رسول اکرم (ص)",
    month: 7,
    day: 27,
  },
  {
    calendar: "jalali",
    official: false,
    title: "جشن سده، گرامیداشتِ کشف آتش به دستِ هوشنگ شاه",
    month: 11,
    day: 10,
  },
  {
    calendar: "jalali",
    official: false,
    title: "بازگشت امام خمینی (ره) به ایران",
    month: 11,
    day: 12,
  },
  {
    calendar: "hijri",
    official: false,
    title: "ولادت سالار شهیدان، امام حسین علیه السلام و روز پاسدار",
    month: 8,
    day: 3,
  },
  {
    calendar: "jalali",
    official: false,
    title: "جشن میانه زمستان",
    month: 11,
    day: 15,
  },
  {
    calendar: "hijri",
    official: false,
    title: "ولادت ابوالفضل العباس علیه السلام و روز جانباز",
    month: 8,
    day: 4,
  },
  {
    calendar: "hijri",
    official: false,
    title: "ولادت امام زین العابدین علیه السلام",
    month: 8,
    day: 5,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز نیروی هوایی",
    month: 11,
    day: 19,
  },
  {
    calendar: "jalali",
    official: true,
    title: "پیروزی انقلاب اسلامی",
    month: 11,
    day: 22,
  },
  {
    calendar: "hijri",
    official: false,
    title: "ولادت علی اکبر علیه السلام و روز جوان",
    month: 8,
    day: 11,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "حمله به سفارت روسیه و قتل گریبایدوف سفیر روسیه تزاری در ایران",
    month: 2,
    day: 11,
  },
  {
    calendar: "hijri",
    official: true,
    title: "ولادت حضرت قائم عجل الله تعالی فرجه و جشن نیمه شعبان",
    month: 8,
    day: 15,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "جشن ولنتاین",
    month: 2,
    day: 14,
  },
  {
    calendar: "jalali",
    official: false,
    title: "جشن سپندارمذگان و روز عشق",
    month: 11,
    day: 29,
  },
  {
    calendar: "jalali",
    official: false,
    title: "فاجعه انفجار قطار نیشابور [1382 خورشیدی]",
    month: 11,
    day: 29,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز بزرگداشت زن و زمین",
    month: 12,
    day: 5,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز بزرگداشت خواجه نصیر الدین طوسی و روز مهندس",
    month: 12,
    day: 5,
  },
  {
    calendar: "jalali",
    official: false,
    title: "سالروز استقلال کانون وکلای دادگستری و روز وکیل مدافع",
    month: 12,
    day: 7,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز درختکاری",
    month: 12,
    day: 15,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روزجهانی زنان",
    month: 3,
    day: 8,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی عدد پی  π",
    month: 3,
    day: 14,
  },
  {
    calendar: "jalali",
    official: false,
    title: "پایان سرایش شاهنامه",
    month: 12,
    day: 25,
  },
  {
    calendar: "jalali",
    official: false,
    title: "روز بزرگداشت اختر چرخ ادب، پروین اعتصامی",
    month: 12,
    day: 25,
  },
  {
    calendar: "hijri",
    official: false,
    title: "ولادت امام حسن مجتبی علیه السلام",
    month: 9,
    day: 15,
  },
  {
    calendar: "jalali",
    official: false,
    title: "جشن چهارشنبه سوری",
    month: 12,
    day: 28,
  },
  {
    calendar: "jalali",
    official: true,
    title: "روز ملی شدن صنعت نفت ایران",
    month: 12,
    day: 29,
  },
  { calendar: "hijri", official: false, title: "شب قدر", month: 9, day: 18 },
  {
    calendar: "hijri",
    official: false,
    title: "ضربت خوردن حضرت علی علیه السلام",
    month: 9,
    day: 19,
  },
  {
    calendar: "jalali",
    official: true,
    title: "آخرین روز سال",
    month: 12,
    day: 30,
  },
  {
    calendar: "gregorian",
    official: false,
    title: "روز جهانی شادی",
    month: 3,
    day: 20,
  },
]
