export * from "./shared"
export * from "./university"
export * from "./major"
export * from "./chart"
export * from "./offering"
export * from "./professor"
export * from "./archive"
export * from "./group"
