import { z } from "zod"

import {
  localizedTextSchema,
  persianYearSchema,
  semesterSchema,
} from "./shared"

/**
 * File: .../majors/<majorSlug>/courses/<year>/<semester>.json
 *
 * A snapshot of the actual course offerings (ارائه‌ها) for ONE academic term,
 * produced by the scraper extension and submitted via PR. The notification
 * pipeline diffs the newest snapshot against the previous one using `index`
 * as the stable key.
 *
 * `<year>` is the academic year folder (plain single year, e.g. 1404).
 */
/**
 * Tolerant schedule/location input: legacy snapshots store `null` or a
 * single string; canonical data (Golestan Excel importer onward) stores
 * arrays — `classSchedule[i]` pairs with `location[i]`. Everything is
 * normalized to an array on parse, so old files keep validating.
 */
function toArray(v: unknown): unknown {
  if (v == null) return []
  if (typeof v === "string") {
    const s = v.trim()
    return s ? [s] : []
  }
  return v
}

const scheduleItem = z.string().min(1).max(255)

export const offeringSchema = z.object({
  /** Offering index (شماره) - THE identity used for change detection. */
  index: z.string().min(1).max(64),
  courseCode: z.string().min(1).max(64),
  courseName: z.string().min(1).max(255),
  courseType: z.string().min(1).max(64).optional(),
  theoreticalUnits: z.number().min(0).max(20).default(0),
  practicalUnits: z.number().min(0).max(20).default(0),
  classCode: z.string().min(1).max(64),

  degree: z.string().min(1).max(128),
  presentationType: z.string().max(128).optional(),

  minCapacity: z.number().int().min(0).nullish(),
  maxCapacity: z.number().int().min(0).nullish(),
  currentEnrollment: z.number().int().min(0).nullish(),

  /** Sessions per week: `["یکشنبه از 07:30 تا 09:30", "سه شنبه از 09:30 تا 11:30"]`. */
  classSchedule: z.preprocess(toArray, z.array(scheduleItem).max(50)),
  examSchedule: z.string().max(255).nullable().default(null),
  professor: z
    .union([
      z.string().max(255),
      localizedTextSchema.pick({ fa: true }).partial({ fa: true }),
    ])
    .nullish(),
  /** Index-matched with classSchedule when lengths align; a single-element
   *  array broadcasts to every session; nulls = unknown. */
  location: z.preprocess(toArray, z.array(scheduleItem.nullable()).max(50)),
})

export type Offering = z.infer<typeof offeringSchema>

export const offeringDocSchema = z.object({
  year: persianYearSchema.optional(),
  semester: semesterSchema.optional(),
  /** ISO timestamp of when the scraper captured this snapshot. */
  scrapedAt: z.iso.datetime(),
  offerings: z.array(offeringSchema).min(0),
})

export type OfferingDoc = z.infer<typeof offeringDocSchema>

/** Diff file: courses/<year>/<semester>/diff.json - generated by sync script, git-aware. */
export const offeringDiffDocSchema = z.object({
  id: z.string().uuid(),
  generatedAt: z.iso.datetime(),
  beforeSha: z.string().nullable(),
  afterSha: z.string().nullable(),
  universitySlug: z.string().min(1),
  majorSlug: z.string().min(1),
  year: persianYearSchema,
  semester: semesterSchema,
  summary: z.object({
    added: z.number().int().min(0),
    removed: z.number().int().min(0),
    changed: z.number().int().min(0),
  }),
  added: z.array(offeringSchema),
  removed: z.array(offeringSchema),
  updated: z.array(
    z.object({
      after: offeringSchema,
      changes: z.array(
        z.object({
          field: z.string(),
          label: z.string(),
          before: z.string().nullable(),
          after: z.string().nullable(),
        })
      ),
    })
  ),
})

export type OfferingDiffDoc = z.infer<typeof offeringDiffDocSchema>
